[model]
data_path = "data.csv"
delimiter = ","
model_path = './model.h5'
text_name = ""
label_name = ""
test_size = 0.2
batch_size=16
n_units = 100
input_shape = 100
epochs = 1

[log]
filename="train.log"
fm="%(asctime)s-%(filename)s-[line:%(lineno)d]-%(levelname)s:%(message)s"
level="INFO"